# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import onvif_pb2 as onvif__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in onvif_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class OnvifServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDeviceInformation = channel.unary_unary(
                '/onvif.OnvifService/GetDeviceInformation',
                request_serializer=onvif__pb2.GetDeviceInformationRequest.SerializeToString,
                response_deserializer=onvif__pb2.GetDeviceInformationResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/onvif.OnvifService/GetCapabilities',
                request_serializer=onvif__pb2.GetCapabilitiesRequest.SerializeToString,
                response_deserializer=onvif__pb2.GetCapabilitiesResponse.FromString,
                _registered_method=True)
        self.GetProfiles = channel.unary_unary(
                '/onvif.OnvifService/GetProfiles',
                request_serializer=onvif__pb2.GetProfilesRequest.SerializeToString,
                response_deserializer=onvif__pb2.GetProfilesResponse.FromString,
                _registered_method=True)
        self.GetStreamUri = channel.unary_unary(
                '/onvif.OnvifService/GetStreamUri',
                request_serializer=onvif__pb2.GetStreamUriRequest.SerializeToString,
                response_deserializer=onvif__pb2.GetStreamUriResponse.FromString,
                _registered_method=True)
        self.AbsoluteMove = channel.unary_unary(
                '/onvif.OnvifService/AbsoluteMove',
                request_serializer=onvif__pb2.AbsoluteMoveRequest.SerializeToString,
                response_deserializer=onvif__pb2.AbsoluteMoveResponse.FromString,
                _registered_method=True)
        self.RelativeMove = channel.unary_unary(
                '/onvif.OnvifService/RelativeMove',
                request_serializer=onvif__pb2.RelativeMoveRequest.SerializeToString,
                response_deserializer=onvif__pb2.RelativeMoveResponse.FromString,
                _registered_method=True)
        self.ContinuousMove = channel.unary_unary(
                '/onvif.OnvifService/ContinuousMove',
                request_serializer=onvif__pb2.ContinuousMoveRequest.SerializeToString,
                response_deserializer=onvif__pb2.ContinuousMoveResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/onvif.OnvifService/Stop',
                request_serializer=onvif__pb2.StopRequest.SerializeToString,
                response_deserializer=onvif__pb2.StopResponse.FromString,
                _registered_method=True)
        self.GetPTZStatus = channel.unary_unary(
                '/onvif.OnvifService/GetPTZStatus',
                request_serializer=onvif__pb2.GetPTZStatusRequest.SerializeToString,
                response_deserializer=onvif__pb2.GetPTZStatusResponse.FromString,
                _registered_method=True)
        self.GetPresets = channel.unary_unary(
                '/onvif.OnvifService/GetPresets',
                request_serializer=onvif__pb2.GetPresetsRequest.SerializeToString,
                response_deserializer=onvif__pb2.GetPresetsResponse.FromString,
                _registered_method=True)
        self.GotoPreset = channel.unary_unary(
                '/onvif.OnvifService/GotoPreset',
                request_serializer=onvif__pb2.GotoPresetRequest.SerializeToString,
                response_deserializer=onvif__pb2.GotoPresetResponse.FromString,
                _registered_method=True)
        self.SetPreset = channel.unary_unary(
                '/onvif.OnvifService/SetPreset',
                request_serializer=onvif__pb2.SetPresetRequest.SerializeToString,
                response_deserializer=onvif__pb2.SetPresetResponse.FromString,
                _registered_method=True)
        self.CreatePreset = channel.unary_unary(
                '/onvif.OnvifService/CreatePreset',
                request_serializer=onvif__pb2.CreatePresetRequest.SerializeToString,
                response_deserializer=onvif__pb2.CreatePresetResponse.FromString,
                _registered_method=True)
        self.RemovePreset = channel.unary_unary(
                '/onvif.OnvifService/RemovePreset',
                request_serializer=onvif__pb2.RemovePresetRequest.SerializeToString,
                response_deserializer=onvif__pb2.RemovePresetResponse.FromString,
                _registered_method=True)
        self.GetPresetTours = channel.unary_unary(
                '/onvif.OnvifService/GetPresetTours',
                request_serializer=onvif__pb2.GetPresetToursRequest.SerializeToString,
                response_deserializer=onvif__pb2.GetPresetToursResponse.FromString,
                _registered_method=True)
        self.CreatePresetTour = channel.unary_unary(
                '/onvif.OnvifService/CreatePresetTour',
                request_serializer=onvif__pb2.CreatePresetTourRequest.SerializeToString,
                response_deserializer=onvif__pb2.CreatePresetTourResponse.FromString,
                _registered_method=True)
        self.ModifyPresetTour = channel.unary_unary(
                '/onvif.OnvifService/ModifyPresetTour',
                request_serializer=onvif__pb2.ModifyPresetTourRequest.SerializeToString,
                response_deserializer=onvif__pb2.ModifyPresetTourResponse.FromString,
                _registered_method=True)
        self.OperatePresetTour = channel.unary_unary(
                '/onvif.OnvifService/OperatePresetTour',
                request_serializer=onvif__pb2.OperatePresetTourRequest.SerializeToString,
                response_deserializer=onvif__pb2.OperatePresetTourResponse.FromString,
                _registered_method=True)
        self.CreateNativePresetTour = channel.unary_unary(
                '/onvif.OnvifService/CreateNativePresetTour',
                request_serializer=onvif__pb2.CreateNativePresetTourRequest.SerializeToString,
                response_deserializer=onvif__pb2.CreateNativePresetTourResponse.FromString,
                _registered_method=True)
        self.ModifyNativePresetTour = channel.unary_unary(
                '/onvif.OnvifService/ModifyNativePresetTour',
                request_serializer=onvif__pb2.ModifyNativePresetTourRequest.SerializeToString,
                response_deserializer=onvif__pb2.ModifyNativePresetTourResponse.FromString,
                _registered_method=True)
        self.OperateNativePresetTour = channel.unary_unary(
                '/onvif.OnvifService/OperateNativePresetTour',
                request_serializer=onvif__pb2.OperateNativePresetTourRequest.SerializeToString,
                response_deserializer=onvif__pb2.OperateNativePresetTourResponse.FromString,
                _registered_method=True)


class OnvifServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetDeviceInformation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStreamUri(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbsoluteMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RelativeMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ContinuousMove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPTZStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GotoPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetPreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePreset(self, request, context):
        """Create a preset with optional desired position/speed; server auto-generates name if empty
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePreset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPresetTours(self, request, context):
        """PTZ Patrol/Preset Tour
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatePresetTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyPresetTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OperatePresetTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateNativePresetTour(self, request, context):
        """Native ONVIF Preset Tour API
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModifyNativePresetTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OperateNativePresetTour(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OnvifServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDeviceInformation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceInformation,
                    request_deserializer=onvif__pb2.GetDeviceInformationRequest.FromString,
                    response_serializer=onvif__pb2.GetDeviceInformationResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=onvif__pb2.GetCapabilitiesRequest.FromString,
                    response_serializer=onvif__pb2.GetCapabilitiesResponse.SerializeToString,
            ),
            'GetProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfiles,
                    request_deserializer=onvif__pb2.GetProfilesRequest.FromString,
                    response_serializer=onvif__pb2.GetProfilesResponse.SerializeToString,
            ),
            'GetStreamUri': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStreamUri,
                    request_deserializer=onvif__pb2.GetStreamUriRequest.FromString,
                    response_serializer=onvif__pb2.GetStreamUriResponse.SerializeToString,
            ),
            'AbsoluteMove': grpc.unary_unary_rpc_method_handler(
                    servicer.AbsoluteMove,
                    request_deserializer=onvif__pb2.AbsoluteMoveRequest.FromString,
                    response_serializer=onvif__pb2.AbsoluteMoveResponse.SerializeToString,
            ),
            'RelativeMove': grpc.unary_unary_rpc_method_handler(
                    servicer.RelativeMove,
                    request_deserializer=onvif__pb2.RelativeMoveRequest.FromString,
                    response_serializer=onvif__pb2.RelativeMoveResponse.SerializeToString,
            ),
            'ContinuousMove': grpc.unary_unary_rpc_method_handler(
                    servicer.ContinuousMove,
                    request_deserializer=onvif__pb2.ContinuousMoveRequest.FromString,
                    response_serializer=onvif__pb2.ContinuousMoveResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=onvif__pb2.StopRequest.FromString,
                    response_serializer=onvif__pb2.StopResponse.SerializeToString,
            ),
            'GetPTZStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPTZStatus,
                    request_deserializer=onvif__pb2.GetPTZStatusRequest.FromString,
                    response_serializer=onvif__pb2.GetPTZStatusResponse.SerializeToString,
            ),
            'GetPresets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresets,
                    request_deserializer=onvif__pb2.GetPresetsRequest.FromString,
                    response_serializer=onvif__pb2.GetPresetsResponse.SerializeToString,
            ),
            'GotoPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.GotoPreset,
                    request_deserializer=onvif__pb2.GotoPresetRequest.FromString,
                    response_serializer=onvif__pb2.GotoPresetResponse.SerializeToString,
            ),
            'SetPreset': grpc.unary_unary_rpc_method_handler(
                    servicer.SetPreset,
                    request_deserializer=onvif__pb2.SetPresetRequest.FromString,
                    response_serializer=onvif__pb2.SetPresetResponse.SerializeToString,
            ),
            'CreatePreset': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePreset,
                    request_deserializer=onvif__pb2.CreatePresetRequest.FromString,
                    response_serializer=onvif__pb2.CreatePresetResponse.SerializeToString,
            ),
            'RemovePreset': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePreset,
                    request_deserializer=onvif__pb2.RemovePresetRequest.FromString,
                    response_serializer=onvif__pb2.RemovePresetResponse.SerializeToString,
            ),
            'GetPresetTours': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPresetTours,
                    request_deserializer=onvif__pb2.GetPresetToursRequest.FromString,
                    response_serializer=onvif__pb2.GetPresetToursResponse.SerializeToString,
            ),
            'CreatePresetTour': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePresetTour,
                    request_deserializer=onvif__pb2.CreatePresetTourRequest.FromString,
                    response_serializer=onvif__pb2.CreatePresetTourResponse.SerializeToString,
            ),
            'ModifyPresetTour': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyPresetTour,
                    request_deserializer=onvif__pb2.ModifyPresetTourRequest.FromString,
                    response_serializer=onvif__pb2.ModifyPresetTourResponse.SerializeToString,
            ),
            'OperatePresetTour': grpc.unary_unary_rpc_method_handler(
                    servicer.OperatePresetTour,
                    request_deserializer=onvif__pb2.OperatePresetTourRequest.FromString,
                    response_serializer=onvif__pb2.OperatePresetTourResponse.SerializeToString,
            ),
            'CreateNativePresetTour': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateNativePresetTour,
                    request_deserializer=onvif__pb2.CreateNativePresetTourRequest.FromString,
                    response_serializer=onvif__pb2.CreateNativePresetTourResponse.SerializeToString,
            ),
            'ModifyNativePresetTour': grpc.unary_unary_rpc_method_handler(
                    servicer.ModifyNativePresetTour,
                    request_deserializer=onvif__pb2.ModifyNativePresetTourRequest.FromString,
                    response_serializer=onvif__pb2.ModifyNativePresetTourResponse.SerializeToString,
            ),
            'OperateNativePresetTour': grpc.unary_unary_rpc_method_handler(
                    servicer.OperateNativePresetTour,
                    request_deserializer=onvif__pb2.OperateNativePresetTourRequest.FromString,
                    response_serializer=onvif__pb2.OperateNativePresetTourResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onvif.OnvifService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('onvif.OnvifService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class OnvifService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetDeviceInformation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/GetDeviceInformation',
            onvif__pb2.GetDeviceInformationRequest.SerializeToString,
            onvif__pb2.GetDeviceInformationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/GetCapabilities',
            onvif__pb2.GetCapabilitiesRequest.SerializeToString,
            onvif__pb2.GetCapabilitiesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/GetProfiles',
            onvif__pb2.GetProfilesRequest.SerializeToString,
            onvif__pb2.GetProfilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStreamUri(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/GetStreamUri',
            onvif__pb2.GetStreamUriRequest.SerializeToString,
            onvif__pb2.GetStreamUriResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbsoluteMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/AbsoluteMove',
            onvif__pb2.AbsoluteMoveRequest.SerializeToString,
            onvif__pb2.AbsoluteMoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RelativeMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/RelativeMove',
            onvif__pb2.RelativeMoveRequest.SerializeToString,
            onvif__pb2.RelativeMoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ContinuousMove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/ContinuousMove',
            onvif__pb2.ContinuousMoveRequest.SerializeToString,
            onvif__pb2.ContinuousMoveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/Stop',
            onvif__pb2.StopRequest.SerializeToString,
            onvif__pb2.StopResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPTZStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/GetPTZStatus',
            onvif__pb2.GetPTZStatusRequest.SerializeToString,
            onvif__pb2.GetPTZStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPresets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/GetPresets',
            onvif__pb2.GetPresetsRequest.SerializeToString,
            onvif__pb2.GetPresetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GotoPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/GotoPreset',
            onvif__pb2.GotoPresetRequest.SerializeToString,
            onvif__pb2.GotoPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetPreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/SetPreset',
            onvif__pb2.SetPresetRequest.SerializeToString,
            onvif__pb2.SetPresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/CreatePreset',
            onvif__pb2.CreatePresetRequest.SerializeToString,
            onvif__pb2.CreatePresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePreset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/RemovePreset',
            onvif__pb2.RemovePresetRequest.SerializeToString,
            onvif__pb2.RemovePresetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPresetTours(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/GetPresetTours',
            onvif__pb2.GetPresetToursRequest.SerializeToString,
            onvif__pb2.GetPresetToursResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreatePresetTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/CreatePresetTour',
            onvif__pb2.CreatePresetTourRequest.SerializeToString,
            onvif__pb2.CreatePresetTourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyPresetTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/ModifyPresetTour',
            onvif__pb2.ModifyPresetTourRequest.SerializeToString,
            onvif__pb2.ModifyPresetTourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OperatePresetTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/OperatePresetTour',
            onvif__pb2.OperatePresetTourRequest.SerializeToString,
            onvif__pb2.OperatePresetTourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateNativePresetTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/CreateNativePresetTour',
            onvif__pb2.CreateNativePresetTourRequest.SerializeToString,
            onvif__pb2.CreateNativePresetTourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModifyNativePresetTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/ModifyNativePresetTour',
            onvif__pb2.ModifyNativePresetTourRequest.SerializeToString,
            onvif__pb2.ModifyNativePresetTourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OperateNativePresetTour(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/onvif.OnvifService/OperateNativePresetTour',
            onvif__pb2.OperateNativePresetTourRequest.SerializeToString,
            onvif__pb2.OperateNativePresetTourResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
